#! /bin/sh

name=zinnia
version=0.2.0
git_url=https://github.com/zinnia-os/zinnia.git
commit=2c534ffbcdc700d82705cc1663a0cf4c8b8411df
imagedeps="git"
allow_network=yes
shallow=no

prepare() {
    git submodule update --init --recursive
}
