#! /bin/sh

name=rust
from_source=rust
revision=2
imagedeps="build-essential cmake ninja-build python3 curl git"
hostdeps="pkg-config"
hostrundeps="gcc llvm"
deps="core-libs rust-libc"
builddeps="mlibc"
allow_network=yes

configure() {
    # Create config.toml for cross-compilation
    cat > config.toml << EOF
change-id = "ignore"

[llvm]
targets = "X86;AArch64;RISCV;LoongArch"
link-shared = true
download-ci-llvm = false

[build]
target = ["${RUST_TRIPLET}", "${RUST_HOST_TRIPLET}"]
docs = false
python = "python3"
tools = ["src"]

[install]
prefix = "${prefix}"
sysconfdir = "etc"

[rust]
channel = "nightly"
codegen-tests = false
deny-warnings = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "${prefix}/bin/llvm-config"

[target.${RUST_TRIPLET}]
llvm-config = "${prefix}/bin/llvm-config"
cc = "${OS_TRIPLET}-gcc"
cxx = "${OS_TRIPLET}-g++"
ar = "${OS_TRIPLET}-ar"
ranlib = "${OS_TRIPLET}-ranlib"
linker = "${OS_TRIPLET}-gcc"
EOF
}


build() {
        BOOTSTRAP_SKIP_TARGET_SANITY=1 \
        CARGO_HOME="${build_dir}/.cargo" \
    ${source_dir}/x.py build rustc std --stage 2 -j${parallelism}
}

package() {
        BOOTSTRAP_SKIP_TARGET_SANITY=1 \
        CARGO_HOME="${build_dir}/.cargo" \
        DESTDIR="${dest_dir}" \
    ${source_dir}/x.py install rustc std --stage 2 -j${parallelism}

    # Remove documentation and other unnecessary files
    rm -rf "${dest_dir}${prefix}"/share/doc
    rm -rf "${dest_dir}${prefix}"/share/man

    # Strip binaries
    strip_command=strip \
    post_package_strip

    # TODO: Install actual source
    mkdir -p "${dest_dir}${prefix}"/lib/rustlib/src/rust/library/
    cp -rp "${source_dir}"/library/. "${dest_dir}${prefix}"/lib/rustlib/src/rust/library/
}
